# name: CI
# on: [push]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - uses: redkubes/docusaurus-deploy-action@v1
#         with:
#           source-folder: website
#           git-user: $SOME_USERNAME
#           git-password: ${{ secrets.GITHUB_TOKEN }}
#           deployment-branch: gh-pages
          